#!/bin/bash

usage () { 
  echo "$(basename $0) prints file with column numbers or specified columns."
  echo "Usage:   $(basename $0) [FILE]     [POS_ARG]..."
  echo "Examples: 
           # prints column numbers
           $(basename $0) access_log

           # prints columns
           $(basename $0) access_log 2 3 5 8" 
  exit 1
}

pipestatus_all_ok () {

  status=($PIPESTATUS)
  for s in $status ; do
    if [ ! $s = 0 ] ; then
      return 1
    fi 
  done
  return 0

}

if [ $# = 0 ] ; then
  usage
fi

# save file path
filepath="$1"
shift

# when no arguments, print column numbers for each line
if [ $# = 0 ] ; then
    awk '{ for ( i=1; i<=NF ; i++ ) printf "$" i " " ; print "" ; print $0}' $filepath  | column -t
    if ! pipestatus_all_ok ; then
      usage
    fi
    exit 0
fi

# parse arguments and prefix it with '$' and suffix with ","
arglist=()
for arg in "$@" ; do
   arglist+=(\$"$arg",) 
done

# the last "," is unnecessary. remove.
lastarg=${arglist[-1]}
arglist[-1]=${lastarg:0:-1}

# awk with new arguments. show usage upon fail.
cat "${filepath}" | awk "{ print ${arglist[*]} }" | column -t
if ! pipestatus_all_ok ; then
  usage
fi
